version: 2
registries:
  public-nuget:
    type: nuget-feed
updates:
  - package-ecosystem: nuget
    directory: "/"
    registries:
      - public-nuget
    schedule:
      interval: daily
      time: "19:27"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 25
    groups:
      Azure:
        patterns:
          - "Azure.*"
          - "Microsoft.Azure.*"
          - "Microsoft.Extensions.Azure"
      AspNetCoreHealthChecks:
        patterns:
          - "AspNetCore.HealthChecks.*"
      AspNetCore:
        patterns:
          - "Microsoft.AspNetCore.*"
          - "Microsoft.Extensions.Features"
      MicrosoftExtensions:
        patterns:
          - "Microsoft.Extensions.*"
      EntityFrameworkCore:
        patterns:
          - "Microsoft.EntityFrameworkCore.*"
      FluentUi:
        patterns:
          - "Microsoft.FluentUI.*"
      OpenTelemetry:
        patterns:
          - "OpenTelemetry.*"
      Npgsql:
        patterns:
          - "Npgsql.*"
      MicrosoftDotNet:
        patterns:
          - "Microsoft.DotNet.*"
      Grpc:
        patterns:
          - "Grpc.*"
    labels:
      - "area-codeflow"
